# Generated by Django 5.2.7 on 2025-11-29 07:11

from django.conf import settings
from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_superuser(apps, schema_editor):
    # Works for default User or custom user model
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)

    username = "Phiri"
    email = "simba_phiri@outlook.com"
    password = "Phiri@123"

    if not User.objects.filter(username=username).exists():
        User.objects.create(
            username=username,
            email=email,
            is_superuser=True,
            is_staff=True,
            is_active=True,
            password=make_password(password),
        )


def delete_superuser(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    User.objects.filter(username="Phiri").delete()


class Migration(migrations.Migration):

    # If your last migration in accounts is not 0001_initial,
    # change this dependency to match the latest file.
    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(create_superuser, delete_superuser),
    ]
