# Generated by Django 5.2.7 on 2025-12-04 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20251129_0911'),
        ('accounts', '0002_create_superuser_phiri'),
    ]

    operations = [
    ]
