# Generated by Django 5.2.7 on 2025-10-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='banner_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tournament',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='tournament',
            name='gallery_urls',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prizes_md',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules_md',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sponsors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tagline',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='tournament',
            name='whatsapp_url',
            field=models.URLField(blank=True),
        ),
    ]
