# Generated by Django 5.2.7 on 2025-10-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_banner_image_tournament_contact_email_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('team', 'tournament'), name='unique_team_per_tournament'),
        ),
    ]
