# Generated by Django 5.2.7 on 2025-10-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_team_draws_team_goals_against_team_goals_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('knockout', 'Knock-out'), ('league', 'League / Round Robin'), ('combination', 'Combination'), ('challenge', 'Challenge')], default='league', max_length=16),
        ),
    ]
