# Generated by Django 5.2.7 on 2025-10-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tournament',
            name='structure',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
