# Generated by Django 5.2.7 on 2025-10-31 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_rules_tournament_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='tournaments.venue'),
        ),
    ]
