# Generated by Django 5.2.7 on 2025-11-06 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_matchscorer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchAssist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assist', to='tournaments.matchscorer')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assists', to='tournaments.match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_assists', to='tournaments.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_assists', to='tournaments.team')),
            ],
            options={
                'unique_together': {('goal',)},
            },
        ),
    ]
