# Generated by Django 5.2.7 on 2025-11-21 16:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_tournament_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Match duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When match was started (set to live)', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 59, 59, 999999), help_text='Tournament end time'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Tournament start time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished')], default='scheduled', max_length=16),
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('passcode', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchReferee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_referees', to='tournaments.match')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_matches', to='tournaments.referee')),
            ],
            options={
                'unique_together': {('match', 'referee')},
            },
        ),
    ]
