# Generated by Django 5.2.7 on 2025-11-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_add_time_fields_and_referee_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='first_prize',
            field=models.DecimalField(decimal_places=2, default=0, help_text='1st place prize amount (e.g., R2000)', max_digits=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='second_prize',
            field=models.DecimalField(decimal_places=2, default=0, help_text='2nd place prize amount (e.g., R500)', max_digits=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='third_prize',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='3rd place prize amount (optional)', max_digits=10, null=True),
        ),
    ]
