# Generated by Django 5.2.7 on 2025-11-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0013_add_prize_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_penalties',
            field=models.PositiveIntegerField(blank=True, help_text='Away team penalty shootout score', null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_penalties',
            field=models.PositiveIntegerField(blank=True, help_text='Home team penalty shootout score', null=True),
        ),
    ]
